kind: pipeline
type: docker
name: default

steps:
- name: glibc-x86_64
  image: gcc
  commands:
    - make clean && make all
    - mv dirl dirl-glibc-x86_64

- name: musl-x86_64
  image: alpine
  commands:
    - apk update && apk add make git build-base linux-headers musl-dev
    - make clean && make STATIC=-static all
    - mv dirl dirl-musl-x86_64

- name: publish binaries
  image: appleboy/drone-scp
  settings:
    host: friedl.net
    username:
      from_secret: deploy_user
    password:
      from_secret: deploy_password
    port: 22
    target: /var/services/dirlist/repo/bin/dirl
    source:
      - dirl-glibc-x86_64
      - dirl-musl-x86_64

- name: publish-container
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: Dockerfile
    purge: true
    repo: arminfriedl/dirl
    tags: latest
