kind: pipeline
type: docker
name: default

steps:
- name: build
  image: gcc
  commands:
    - make

- name: run
  image: debian
  commands:
    - cp quark /usr/local/bin
    - useradd web && su web && cd
    - mkdir -p web && cd web && echo "hello from quark" > index.html 
    - quark -p 9130 -h run -l -u web -g web
  detach: true

- name: test
  image: curlimages/curl
  commands:
    - sleep 15
    - curl http://run:9130
